---
kind: wasmer.io/App.v0
name: aurora-sync
description: AuroraSync - lightweight data sync service (FastAPI)
package: .
debug: true
env:
  PYTHONEXECUTABLE: /bin/python
  PYTHONPATH: /src
  PORT: "80"
  ADMIN_PASSWORD: "admin"
  AURORA_DOMAIN: "aurora-sync.wasmer.app"
scaling:
  mode: single_concurrency
